language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      rvm: system

branches:
  only:
    - master

install:
  - unset DYLD_LIBRARY_PATH
  - export HOMEBREW_DEVELOPER=1
  - mkdir -p $(brew --repo)/Library/Taps/dpo
  - ln -s "$TRAVIS_BUILD_DIR" $(brew --repo)/Library/Taps/dpo/homebrew-julia
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/dpo/homebrew-julia"
  - chmod 0644 $(brew --repo)/Library/Taps/dpo/homebrew-julia/*.rb
  - brew tap --repair
  - brew update

script:
  - brew test-bot --tap=dpo/julia
